services:
  - type: web
    name: calculator-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: calculator-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: calculator-backend
          property: host
      - key: REACT_APP_SOCKET_URL
        fromService:
          type: web
          name: calculator-backend
          property: host
